pipeline {
  agent {
    docker {
      image 'maven:3.9.6-eclipse-temurin-17'
      args '-v $HOME/.m2:/root/.m2'
    }
  }
  environment {
    MAVEN_OPTS = '-Dmaven.repo.local=.m2/repository'
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build & Test') {
      steps {
        sh 'mvn clean test'
      }
    }
  }
  post {
    always {
      junit 'target/surefire-reports/**/*.xml'
      archiveArtifacts artifacts: 'target/**/*.jar', allowEmptyArchive: true
    }
  }
}
