# Browser Configuration
browser=chrome

# Application URL
url=https://devstacklms.vercel.app/auth/login

# Admin Credentials
admin.email=super@admin.com
admin.password=password

# Student Credentials
student.email=student1@library.com
student.password=password